server:
  port: 9901
  servlet:
    context-path: "/hotel-search-service"

info:
  app:
    name: '@project.name@'
    version: '@project.version@'

spring:
  application:
    name: '@project.name@'

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitoring

supplier:
  endPoint:
    requestorId: "traveldoo_test"
    credential: "C2A43182"
    url: "https://traveldoo.koedia.com"

grpc:
  client:
    grpc-hotelAvailable-servic:
      address: static://localhost:9901
      negotiationType: plaintext

