server:
  port: 8085
  servlet:
    context-path: "/hotel-search-service"

info:
  app:
    name: '@project.name@'
    version: '@project.version@'

spring:
  application:
    name: HOTEL-SEARCH-API

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitoring

supplier:
  endPoint:
    requestorId: "DJANTLmP90QE"
    credential: "aWVhLc6g"
    url: "https://traveldoo.koedia.com"

grpc:
  client:
    hotel-availibility-pad:
      address: 'discovery:///hotel-availibility-pad'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka/