---
apiVersion: v1
kind: Service
metadata:
  name: hotel-search-service
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app.kubernetes.io/name: hotel-search-service